Vagrant.configure("2") do |config|
  config.vm.box = "jonascrecencio/eve-ng"
  config.vm.box_version = "0.0.1"

  config.vm.define :eveng do |config_eveng|
    config_eveng.vm.hostname = "eve-ng"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/guest.yml"
  end
  config.vm.provider :libvirt do |domain|
    domain.memory = 4096
    domain.cpus = 2
    domain.autostart = true
    domain.nested = true
  end
end
end