Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.define :analyzer01 do |config_analyzer01|
    config_analyzer01.vm.hostname = "analyzer01"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/guest.yml"
  end
  config.vm.provider :libvirt do |domain|
    domain.memory = 1024
    domain.cpus = 1
    domain.autostart = true
  end
end
end