---
- name: Install devOps server Lab
  hosts:  all
  become: yes
  strategy: free

  roles:
    - ../../../lib/ansible/roles/name
    - ../../../lib/ansible/roles/post-install
    - ../../../lib/ansible/roles/repos
    - ../../../lib/ansible/roles/utils
    - ../../../lib/ansible/roles/kvm
    - ../../../lib/ansible/roles/vagrant
    - ../../../lib/ansible/roles/ansible
    
  vars_files:
    - ../vars/main.yml